# Generated by Django 4.2.7 on 2023-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial=True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('img1', models.ImageField(upload_to='photos')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
